//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "VueDes.h"
using namespace VueInterfaces;
#include<vector>

namespace VueImplementation
{
	class VueDesImpl : public VueDes
	{
		private :


		protected :


		public :


		private :


		protected :


		public :

			virtual void update();
			virtual void getModele();

	}; 
	EXTERNC DLL void VUEDESIMPL_update(VueDesImpl*);
	EXTERNC DLL void VUEDESIMPL_getModele(VueDesImpl*);
} 

