//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Plateau.h"
using namespace VueInterfaces;
#include "VuePlateau.h"
using namespace VueInterfaces;
#include "Vaisseau.h"
using namespace VueInterfaces;
#include "VueVaisseau.h"
using namespace VueInterfaces;
#include "Des.h"
using namespace VueInterfaces;
#include "VueDes.h"
using namespace VueInterfaces;
#include "VueFabrique.h"
using namespace VueInterfaces;
#include<vector>

namespace VueImplementation
{
	class VueFabriqueImpl : public VueFabrique
	{
		private :


		protected :


		public :


		private :


		protected :


		public :

			virtual VuePlateau creerVuePlateau(Plateau Modele);
			virtual VueVaisseau creerVueVaisseau(Vaisseau Modele);
			virtual VueDes creerVueDes(Des Modele);

	}; 
	EXTERNC DLL VuePlateau VUEFABRIQUEIMPL_creerVuePlateau(VueFabriqueImpl*, Plateau Modele);
	EXTERNC DLL VueVaisseau VUEFABRIQUEIMPL_creerVueVaisseau(VueFabriqueImpl*, Vaisseau Modele);
	EXTERNC DLL VueDes VUEFABRIQUEIMPL_creerVueDes(VueFabriqueImpl*, Des Modele);
} 

