//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "VueGestionTir.h"
using namespace VueInterfaces;
#include<vector>

namespace VueImplementation
{
	class VueGestionTirImpl : public VueGestionTir
	{
		private :


		protected :


		public :


		private :


		protected :


		public :

			virtual void update();

	}; 
	EXTERNC DLL void VUEGESTIONTIRIMPL_update(VueGestionTirImpl*);
} 

