//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

namespace ModeleInterfaces
{
	class Plateau 
	{
		public:
		virtual void casesAccessibles(object int xOrig, object int yOrig, object int resultDe)=0;

		virtual void gestionTir()=0;

		virtual void initialiserPlateau()=0;

		virtual void verifierCaseArrivee(object int x, object int y))=0;

	};
	EXTERNC DLL void PLATEAU_casesAccessibles(Plateau*, object int xOrig, object int yOrig, object int resultDe);
	EXTERNC DLL void PLATEAU_gestionTir(Plateau*);
	EXTERNC DLL void PLATEAU_initialiserPlateau(Plateau*);
	EXTERNC DLL void PLATEAU_verifierCaseArrivee(Plateau*, object int x, object int y));
}

