//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "int.h"
#include "FabriqueConcreteVaisseau.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class Battlecruiser : public FabriqueConcreteVaisseau
	{
		private :


		protected :


		public :

			static int chargeMax;
			static int nbDes;

		private :


		protected :


		public :


	}; 
} 

