//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "list.h"
#include "Case.h"
using namespace ModeleImplementation;
#include "Coordonnee.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class CaseAsteroide : public Case
	{
		private :

			list coordonnee;

		protected :

			std::vector<Coordonnee> Coordonnee;

		public :


		private :


		protected :


		public :

			virtual void getCoordonnee();

	}; 
	EXTERNC DLL void CASEASTEROIDE_getCoordonnee(CaseAsteroide*);
} 

