//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Couleur.h"
#include "Case.h"
using namespace ModeleImplementation;
#include "Couleur.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class CaseStationOrbitale : public Case
	{
		private :

			Couleur couleur;

		protected :

			Couleur Couleur;

		public :


		private :


		protected :


		public :


	}; 
} 

