//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "int.h"
#include "De.h"
using namespace ModeleInterfaces;
#include<vector>

namespace ModeleImplementation
{
	class DeImpl : public De
	{
		private :

			int valeur;

		protected :


		public :


		private :


		protected :


		public :

			virtual void lancerDe();

	}; 
	EXTERNC DLL void DEIMPL_lancerDe(DeImpl*);
} 

