//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include<vector>

namespace ModeleImplementation
{
	/// <remarks>Patron de Conception : "MONTEUR"</remarks>
	class MonteurPartie
	{
		private :


		protected :


		public :


		private :


		protected :


		public :

			virtual void initJoueurs();
			virtual void creerPlateau(object file f);
			virtual void creerDes();

	}; 
	EXTERNC DLL void MONTEURPARTIE_initJoueurs(MonteurPartie*);
	EXTERNC DLL void MONTEURPARTIE_creerPlateau(MonteurPartie*, object file f);
	EXTERNC DLL void MONTEURPARTIE_creerDes(MonteurPartie*);
} 

