//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Partie.h"
using namespace ModeleInterfaces;
#include "JoueurImpl.h"
using namespace ModeleImplementation;
#include "DeImpl.h"
using namespace ModeleImplementation;
#include "PlateauImpl.h"
using namespace ModeleImplementation;
#include "MonteurPartie.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class PartieImpl : public Partie
	{
		private :


		protected :

			std::vector<JoueurImpl> Joueur;
			std::vector<DeImpl> Des;
			PlateauImpl Plateau1;
			MonteurPartie MonteurPartie;

		public :


		private :


		protected :


		public :

			virtual void construirePartie();
			virtual void initialiserOrdreJoueurs();

	}; 
	EXTERNC DLL void PARTIEIMPL_construirePartie(PartieImpl*);
	EXTERNC DLL void PARTIEIMPL_initialiserOrdreJoueurs(PartieImpl*);
} 

