//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "int.h"
#include "Case[][].h"
#include "Plateau.h"
using namespace ModeleInterfaces;
#include "FabriqueCase.h"
using namespace ModeleImplementation;
#include "Case.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class PlateauImpl : public Plateau
	{
		private :

			int largeur;
			int longueur;
			Case[][] plateau;

		protected :

			FabriqueCase FabriqueCase;
			std::vector<Case> Case;

		public :


		private :


		protected :


		public :

			virtual void casesAccessibles(object int xOrig, object int yOrig, object int resultDe);
			virtual void initialiserPlateau();
			virtual void gestionTir();
			virtual void verifierCaseArrivee(object int x, object int y));

	}; 
	EXTERNC DLL void PLATEAUIMPL_casesAccessibles(PlateauImpl*, object int xOrig, object int yOrig, object int resultDe);
	EXTERNC DLL void PLATEAUIMPL_initialiserPlateau(PlateauImpl*);
	EXTERNC DLL void PLATEAUIMPL_gestionTir(PlateauImpl*);
	EXTERNC DLL void PLATEAUIMPL_verifierCaseArrivee(PlateauImpl*, object int x, object int y));
} 

