//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "int.h"
#include "Joueur.h"
using namespace ModeleInterfaces;
#include "VaisseauConcret.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class JoueurImpl : public Joueur
	{
		private :

			int nbArtefacts;
			int nbFlottes;

		protected :

			VaisseauConcret VaisseauConcret;

		public :


		private :


		protected :


		public :

			virtual void deplacer();
			virtual void tirer(object float angle);
			virtual void lancerDe();
			virtual void initialiserJoueur();
			virtual void deposerArtefact();

	}; 
	EXTERNC DLL void JOUEURIMPL_deplacer(JoueurImpl*);
	EXTERNC DLL void JOUEURIMPL_tirer(JoueurImpl*, object float angle);
	EXTERNC DLL void JOUEURIMPL_lancerDe(JoueurImpl*);
	EXTERNC DLL void JOUEURIMPL_initialiserJoueur(JoueurImpl*);
	EXTERNC DLL void JOUEURIMPL_deposerArtefact(JoueurImpl*);
} 

