//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "MonteurPartie.h"
using namespace ModeleImplementation;
#include<vector>

namespace ModeleImplementation
{
	class MonteurPartie4Joueurs : public MonteurPartie
	{
		private :


		protected :


		public :


		private :


		protected :


		public :

			override void creerPlateau(object file f);

	}; 
	EXTERNC DLL void MONTEURPARTIE4JOUEURS_creerPlateau(MonteurPartie4Joueurs*, object file f);
} 

