//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

namespace ModeleInterfaces
{
	class Partie 
	{
		public:
		virtual void construirePartie()=0;

		virtual void initialiserOrdreJoueurs()=0;

	};
	EXTERNC DLL void PARTIE_construirePartie(Partie*);
	EXTERNC DLL void PARTIE_initialiserOrdreJoueurs(Partie*);
}

