//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "int.h"
#include<vector>

namespace ModeleImplementation
{
	class Position
	{
		private :

			int x;
			int y;

		protected :


		public :


		private :


		protected :


		public :

			virtual void getX();
			virtual void getY();
			virtual void setX(object int x);
			virtual void setY(object int y);

	}; 
	EXTERNC DLL void POSITION_getX(Position*);
	EXTERNC DLL void POSITION_getY(Position*);
	EXTERNC DLL void POSITION_setX(Position*, object int x);
	EXTERNC DLL void POSITION_setY(Position*, object int y);
} 

