//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif

namespace ModeleInterfaces
{
	class Vaisseau 
	{
		public:
		virtual void deplacerVaisseau()=0;

		virtual void detruireVaisseau()=0;

		virtual void possedeArtefact()=0;

		virtual void rechargerVaisseau()=0;

		virtual void chargerArtefact()=0;

		virtual void getNbCharges(object )()=0;

	};
	EXTERNC DLL void VAISSEAU_deplacerVaisseau(Vaisseau*);
	EXTERNC DLL void VAISSEAU_detruireVaisseau(Vaisseau*);
	EXTERNC DLL void VAISSEAU_possedeArtefact(Vaisseau*);
	EXTERNC DLL void VAISSEAU_rechargerVaisseau(Vaisseau*);
	EXTERNC DLL void VAISSEAU_chargerArtefact(Vaisseau*);
	EXTERNC DLL void VAISSEAU_getNbCharges(Vaisseau*, object )();
}

