//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Plateau.h"
using namespace VueInterfaces;
#include "VuePlateau.h"
using namespace VueInterfaces;
#include "Vaisseau.h"
using namespace VueInterfaces;
#include "VueVaisseau.h"
using namespace VueInterfaces;
#include "Des.h"
using namespace VueInterfaces;
#include "VueDes.h"
using namespace VueInterfaces;

namespace VueInterfaces
{
	class VueFabrique 
	{
		public:
		virtual VuePlateau creerVuePlateau(Plateau Modele)=0;

		virtual VueVaisseau creerVueVaisseau(Vaisseau Modele)=0;

		virtual VueDes creerVueDes(Des Modele)=0;

	};
	EXTERNC DLL VuePlateau VUEFABRIQUE_creerVuePlateau(VueFabrique*, Plateau Modele);
	EXTERNC DLL VueVaisseau VUEFABRIQUE_creerVueVaisseau(VueFabrique*, Vaisseau Modele);
	EXTERNC DLL VueDes VUEFABRIQUE_creerVueDes(VueFabrique*, Des Modele);
}

