//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Observer.h"

namespace VueInterfaces
{
	/// <remarks>Patron de Conception : OBSERVATEUR</remarks>
	class VueVaisseau  : public Observer
	{
		public:
		virtual void getModele()=0;

	};
	EXTERNC DLL void VUEVAISSEAU_getModele(VueVaisseau*);
}

