//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma once
#define WANTDLLEXP
#ifdef WANTDLLEXP		//exportation dll
#define DLL  __declspec( dllexport )
#define EXTERNC extern "C"
#else
#define DLL		//standard
#define EXTERNC
#endif
#include "Command.h"
using namespace ControleurCommand;
#include<vector>

namespace ControleurCommand
{
	class DeplacerVaisseau : public Command
	{
		private :


		protected :


		public :


		private :


		protected :


		public :

			override void doIt();
			virtual void canDo();

	}; 
	EXTERNC DLL void DEPLACERVAISSEAU_doIt(DeplacerVaisseau*);
	EXTERNC DLL void DEPLACERVAISSEAU_canDo(DeplacerVaisseau*);
} 

